kind = "web"
previewPath = "/"
title = "Wisata Indonesia"
version = "1.0.0"
id = "artifacts/wisata-indonesia"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20081

[services.development]
run = "pnpm --filter @workspace/wisata-indonesia run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wisata-indonesia", "run", "build" ]
publicDir = "artifacts/wisata-indonesia/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20081"
BASE_PATH = "/"
